nameOverride: react-app-uat
fullnameOverride: react-app-uat

global:
  replicaCount: 2
  namespace: react-app-uat

deployment:
  image:
    name: "docker.io/vishu0210/react-app-uat"
    tag: "latest"

  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi

  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

service:
  type: ClusterIP
  specs:
    - name: http
      port: 80
      targetPort: 3000

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: react-app-uat-uat.example.com
      paths:
        - path: /
          pathType: Prefix


pdb:
  enabled: false
  minAvailable: 1


configmap:
  enabled: false
  data: {}


secret:
  enabled: false
  data: {}


networkPolicy:
  enabled: false

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 70
  targetMemory: 80
