apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
    app: react-app-dev
spec:
  project: dev
  source:
    repoURL: 
    targetRevision: HEAD
    path: helm/platform-app
    helm:
      valueFiles:
        - values.yaml
        - ../../applications/app7/dev-values.yaml
  destination:
    server: https://dev-eks-endpoint.eks.amazonaws.com
    namespace: react-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
